name: Build and test .Net

on: 
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:

    runs-on: ubuntu-lastest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build all project
      run: dotnet restore --no-restore --configuration Release

    - name: Test BackendServer.UnitTest
      run: dotnet test ./Tests/KnowledgeSpace.BackendServer.UnitTest/KnowledgeSpace.BackendServer.UnitTest.csproj --no-build --verbosity normal
    - name: Test ViewModel.UnitTest
      run: dotnet test ./Tests/KnowledgeSpace.ViewModels.UnitTest/.UnitTest/KnowledgeSpace.ViewModels.UnitTest.csproj --no-build --verbosity normal
